name: "Kubeconform action"
description: "Generate manifests with `helm template` and run `kubeconform` on the results"
author: "WDaan"
inputs:
  strict:
    description: "Whether to run Kubeconform in strict mode"
    default: "true"
    required: false
  additionalSchemaPaths:
    description: "Newline-separated list of paths to look for schemas under, including filename template"
    default: ""
    required: false
  chartsDirectory:
    description: "Directory to search for chart directories under"
    default: "charts"
    required: true
  kubernetesVersion:
    description: "Version of Kubernetes to validate manifests against"
    default: "master"
    required: false
  ignoreMissingSchemas:
    description: "Skip files with missing schemas instead of failing"
    default: "false"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    KUBECONFORM_STRICT: "${{ inputs.strict }}"
    ADDITIONAL_SCHEMA_PATHS: "${{ inputs.additionalSchemaPaths }}"
    CHARTS_DIRECTORY: "${{ inputs.chartsDirectory }}"
    HELM_UPDATE_DEPENDENCIES: "true"
    KUBERNETES_VERSION: "${{ inputs.kubernetesVersion }}"
    IGNORE_MISSING_SCHEMAS: "${{ inputs.ignoreMissingSchemas }}"

branding:
  color: blue
  icon: check-square