name: Build and publish to ghcr.io

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  IMAGE: ghcr.io/${{ github.repository }}
  HELM_VERSION: v3.9.4
  K8S_SCHEMA_UPSTREAM: "master"
  KUBECONFORM_VERSION: "v0.4.14"
  GO_VERSION: "1.19.2"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: sanitize version
        run: |
          VERSION=${{github.ref_name}}
          echo "VERSION=${VERSION:1}" >> $GITHUB_ENV
      
      - name: zLogin to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE }}
          labels: |
            tools.helm.version=${{ env.HELM_VERSION }}
            tools.kubeconform.version=${{ env.KUBECONFORM_VERSION }}
            kubernetes.schema.version=${{ env.K8S_SCHEMA_UPSTREAM }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
     
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GO_VERSION=${{ env.GO_VERSION }}
            KUBECONFORM_VERSION=${{ env.KUBECONFORM_VERSION }}
            HELM_VERSION=${{ env.HELM_VERSION }}
            SCHEMA_REVISION=${{ env.K8S_SCHEMA_UPSTREAM }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            README.md
            *.tgz
